export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const CHARTS_REQUEST = 'CHARTS_REQUEST'
export const CHARTS_SUCCESS = 'CHARTS_SUCCESS'

export const MONITOR_REQUEST = 'MONITOR_REQUEST'
export const MONITOR_SUCCESS = 'MONITOR_SUCCESS'

export const WORKPLACE_REQUEST = 'WORKPLACE_REQUEST'
export const WORKPLACE_SUCCESS = 'WORKPLACE_SUCCESS'
